#!/bin/bash

set -eu

echo '      ___               ____  ______ _____  _____   '
echo '     / _ | ___  ___    /_  / / __/ // / _ \/ ___/   '
echo '    / __ |/ _ \/ _ \    / /__\ \/ _  / , _/ /__     '
echo '   /_/ |_/_//_/\___/   /___/___/_//_/_/|_|\___/     '
echo '                                                    '
AZ_INSTALLING=1
AZ_SRC="https://raw.githubusercontent.com/Anonoei/anozsh/main/"

AZ_COPY() {
    if [[ $AZ_SRC == /* ]]; then
        cp "$1" "$2"
    else
        curl -L -o "$2" "$1"
    fi
}

if [ "$1" == "-c" ]; then
    rm -rf "${HOME}/.local/anozsh/plugins"
    shift
fi

if [ "$1" == "-u" ]; then
    if [ -f "${HOME}/.local/anozsh/az_settings.zsh" ]; then
        rm "${HOME}/.local/anozsh/az_settings.zsh"
    fi
    if [ -f "${HOME}/.local/anozsh/starship.toml" ]; then
        rm  "${HOME}/.local/anozsh/starship.toml"
    fi
    shift
fi

if [ "$1" == "-r" ]; then
    rm -rf "${HOME}/.local/anozsh"
    shift
fi

if [ "$1" == "-l" ]; then
    AZ_SRC="$2"
    if [ "$AZ_SRC" == "." ]; then
        AZ_SRC="$PWD"
    fi
    foldername=${AZ_SRC##*/}
    foldername=${foldername:-/}
    if [ ! $foldername == "anozsh" ]; then
        echo "Please install from anozsh source, not $foldername"
        exit
    fi
    if [ ! -d "$AZ_SRC" ]; then
        echo "Unable to install from local directory $AZ_SRC"
        exit
    fi
fi

install_package() {
    echo "Installing $1..."
    if  [ -x "$(command -v nala)" ];     then sudo nala install $1
    elif [ -x "$(command -v apt-get)" ]; then sudo apt install $1
    elif [ -x "$(command -v apk)" ];     then sudo apk add --no-cache $1
    elif [ -x "$(command -v dnf)" ];     then sudo dnf install $1
    elif [ -x "$(command -v pacman)" ];  then sudo pacman -Syu $1
    elif [ -x "$(command -v zypper)" ];  then sudo zypper install $1
    elif [ -x "$(command -v brew)" ];    then brew install $1
    else echo "FAILED TO INSTALL PACKAGE: Package manager not found. You must manually install: $packagesNeeded">&2; fi
}

verify_zsh_installed() {
    output=$(zsh --version)
    installed=0
    while IFS= read -r line; do
        if [[ $line == *"zsh "* ]]; then
            installed=1
        fi
    done <<< "$output"
    if [ $installed == 0 ]; then
        echo "ZSH is not installed. Installing ZSH..."
        packagesNeeded='zsh'
        install_package "zsh"
    fi
}

verify_zsh_default() {
    if [[ ! $SHELL == *"/bin/zsh"* ]]; then
        echo "ZSH is not the default shell. Setting ZSH to default..."
        chsh -s $(which zsh)
    fi
}

cd "${HOME}"
echo "Installing from $AZ_SRC"

verify_zsh_installed
verify_zsh_default

echo "Installing dependencies"
for pkg in "bat" "tree" "multitail" "fastfetch"; do
    install_package $pkg
done

echo "Downloading AnoZSH .zshrc file"
AZ_COPY "$AZ_SRC/.zshrc" "${HOME}/.zshrc"
mv "${HOME}/.zshrc" "${HOME}/.zshrc_tmp"

sed "s|ANOZSH_SRC=.*|ANOZSH_SRC=\"$AZ_SRC\"|g" "${HOME}/.zshrc_tmp" > "${HOME}/.zshrc"
rm "${HOME}/.zshrc_tmp"

if [ ! -d "$HOME/.local/anozsh" ]; then
    echo 'Creating ~/.local/anozsh'
    mkdir -p "${HOME}/.local/anozsh"
else
    echo "Cleaning ~/.local/anozsh"
    find "${HOME}/.local/anozsh" -type f -name "az*.zsh" -not -name 'az_settings.zsh' -print0 | xargs -0 rm --
fi

echo "Downloading AnoZSH az_main"
AZ_COPY "$AZ_SRC/anozsh/az_main.zsh" "${HOME}/.local/anozsh/az_main.zsh"
echo "Installed! Running AnoZSH"
for _ in "" "" "" "" "" ""; do
    sleep .5
    echo -n "."
done
clear
exec zsh
