#!/bin/bash
echo '      ___               ____  ______ _____  _____   '
echo '     / _ | ___  ___    /_  / / __/ // / _ \/ ___/   '
echo '    / __ |/ _ \/ _ \    / /__\ \/ _  / , _/ /__     '
echo '   /_/ |_/_//_/\___/   /___/___/_//_/_/|_|\___/     '
echo '                                                    '
cd "${HOME}"

ZSH_INSTALLED=0
ZSH_DEFAULT=0

output=$(zsh --version)
while IFS= read -r line; do
    if [[ $line == *"zsh "* ]]; then
        ZSH_INSTALLED=1
    fi
done <<< "$output"

if [[ $SHELL == *"/bin/zsh"* ]]; then
    ZSH_DEFAULT=1
fi

if [ $ZSH_INSTALLED == 0 ]; then
    echo "ZSH is not installed. Installing ZSH..."
    packagesNeeded='zsh'
    if [ -x "$(command -v apk)" ];       then sudo apk add --no-cache $packagesNeeded
    elif [ -x "$(command -v apt-get)" ]; then sudo apt-get install $packagesNeeded
    elif [ -x "$(command -v dnf)" ];     then sudo dnf install $packagesNeeded
    elif [ -x "$(command -v zypper)" ];  then sudo zypper install $packagesNeeded
    else echo "FAILED TO INSTALL PACKAGE: Package manager not found. You must manually install: $packagesNeeded">&2; fi
fi

if [ $ZSH_DEFAULT == 0 ]; then
    echo "ZSH is not the default shell. Setting ZSH to default..."
    chsh -s $(which zsh)
fi

echo "Downloading ANOZSH .zshrc file"
curl -L -o "${HOME}/.zshrc" https://raw.githubusercontent.com/Anonoei/anozsh/main/.zshrc
if [[ ! -d "${HOME}/.local/anozsh" ]]; then
    echo 'Creating ~/.local/anozsh'
    mkdir -p "${HOME}/.local/anozsh"
fi

echo "Downloading ANOZSH az_main"
curl -L -o "${HOME}/.local/anozsh/az_main.zsh" https://raw.githubusercontent.com/Anonoei/anozsh/main/anozsh/az_main.zsh 
echo "Done! Restarting terminal..."
exec zsh