#!/bin/bash

if command -v apt &> /dev/null; then # Debian
  echo "apt"
elif command -v yum &> /dev/null; then # RHEL
  echo "yum"
elif command -v dnf &> /dev/null; then # RHEL
  echo "dnf"
elif command -v zypper &> /dev/null; then # OpenSUSE
  echo "zypper"
elif command -v pacman &> /dev/null; then # Arch
  echo "pacman"
elif command -v portage &> /dev/null; then # Gentoo
  echo "portage"
elif command -v slackpkg &> /dev/null; then # Slackware
  echo "slackpkg"
elif command -v brew &> /dev/null; then # MacOS?
  echo "brew"
else
  echo ""
fi
